version: "3.8"

services:
  binance-pump-alerts:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: patbaumgartner/binance-pump-alerts:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}
      - PUMP_EMOJI=${PUMP_EMOJI}
      - DUMP_EMOJI=${DUMP_EMOJI}
      - NO_OF_REPORTED_COINS=${NO_OF_REPORTED_COINS}
      - DEBUG=${DEBUG}
      - RESET_INTERVAL=${RESET_INTERVAL}
      - HEALTH_PING_ENABLED=${HEALTH_PING_ENABLED:-true}
      - HEALTH_PING_INTERVAL=${HEALTH_PING_INTERVAL:-3600}
      - EMAIL_ENABLED=${EMAIL_ENABLED:-false}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
